var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/resource/resolve/route.js")
R.c("server/chunks/[root-of-the-server]__0sy_ccc._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_0s77-mv._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_resource_resolve_route_actions_1xp5cfz.js")
R.m(133347)
module.exports=R.m(133347).exports
