var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/draft/route.js")
R.c("server/chunks/[root-of-the-server]__0l25fh6._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_0s77-mv._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_draft_route_actions_1h8a540.js")
R.m(134563)
module.exports=R.m(134563).exports
