import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/kairo/LegalPage";

export const metadata: Metadata = { title: "Terms · Solaspace" };

const CONTACT = "zander.leon@gmail.com";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 2026">
      <p>
        These terms cover your use of Solaspace, operated by Zander Leon (&ldquo;Solaspace,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating
        an account or using the app, you agree to them. If you don&rsquo;t agree, please don&rsquo;t use the service.
      </p>

      <LegalSection heading="The service">
        <p>
          Solaspace turns goals into plans and helps you decide what to do next. Features may change as we improve the
          product.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <p>
          You&rsquo;re responsible for keeping your account secure and for the content you create. Don&rsquo;t use Solaspace
          for anything unlawful, or to disrupt, abuse, or overload the service.
        </p>
      </LegalSection>

      <LegalSection heading="AI-generated plans">
        <p>
          Plans, breakdowns, and answers are generated by AI and are suggestions to help you act — not professional,
          legal, medical, or financial advice. Use your own judgment, and verify anything important.
        </p>
      </LegalSection>

      <LegalSection heading="Subscriptions &amp; billing">
        <p>
          Solaspace has a free plan and a paid <strong>Pro</strong> subscription. Pro is billed in advance on a recurring
          basis — monthly ($12/month) or yearly ($96/year) — through our payment processor, Stripe. Applicable taxes may
          be added.
        </p>
        <p>
          <strong>Automatic renewal.</strong> Your subscription renews automatically at the end of each billing period at
          the then-current price, and your payment method is charged, until you cancel.
        </p>
        <p>
          <strong>Cancelling.</strong> You can cancel anytime from Settings &rarr; Manage plan, which opens the Stripe
          billing portal. Cancelling stops future renewals; you keep Pro access through the end of the period you&rsquo;ve
          already paid for.
        </p>
        <p>
          <strong>Refunds.</strong> Payments are non-refundable except where required by law. If you&rsquo;re in the EU or
          UK, you have a statutory 14-day right to withdraw from a new purchase; by choosing to start using Pro right away
          you ask us to begin the service within that period. If you were charged in error or something goes wrong, email
          us and we&rsquo;ll make it right.
        </p>
        <p>
          <strong>Price changes.</strong> We may change prices; we&rsquo;ll give you notice before a change affects your
          renewals.
        </p>
      </LegalSection>

      <LegalSection heading="Availability and warranty">
        <p>
          The service is provided &ldquo;as is,&rdquo; without warranties of any kind. We work to keep Solaspace reliable but
          can&rsquo;t guarantee it will be uninterrupted or error-free.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>
          To the extent permitted by law, Solaspace is not liable for indirect or consequential damages arising from your
          use of the service.
        </p>
      </LegalSection>

      <LegalSection heading="Ending your use">
        <p>
          You can delete your account at any time from Settings. We may suspend accounts that violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <p>
          We may update these terms; we&rsquo;ll revise the date above when we do. Questions? Email{" "}
          <a href={`mailto:${CONTACT}`} className="text-accent underline underline-offset-2">{CONTACT}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
