var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/ask-node/route.js")
R.c("server/chunks/[root-of-the-server]__1uoxegi._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/_0s77-mv._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_ask-node_route_actions_1l3pcol.js")
R.m(584545)
module.exports=R.m(584545).exports
