var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/goal-map/route.js")
R.c("server/chunks/[root-of-the-server]__1gx-ert._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0esc6by.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_0s77-mv._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_goal-map_route_actions_00frp1w.js")
R.m(8829)
module.exports=R.m(8829).exports
