// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/admin" | "/app/billing" | "/app/inbox" | "/app/map" | "/app/notebook" | "/app/review" | "/app/settings" | "/app/today" | "/gate" | "/onboarding" | "/privacy" | "/s/[token]" | "/sign-in" | "/sign-up" | "/terms"
type AppRouteHandlerRoutes = "/api/ai/ask-node" | "/api/ai/ask-sola" | "/api/ai/clarify" | "/api/ai/draft" | "/api/ai/expand-node" | "/api/ai/extract-steps" | "/api/ai/goal-map" | "/api/ai/replan" | "/api/ai/research" | "/api/ai/unblock" | "/api/ai/work-session" | "/api/cron/notifications" | "/api/gate" | "/api/health" | "/api/resource/resolve" | "/api/stripe/checkout" | "/api/stripe/portal" | "/api/stripe/webhook" | "/api/unsubscribe"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/ask-node": {}
  "/api/ai/ask-sola": {}
  "/api/ai/clarify": {}
  "/api/ai/draft": {}
  "/api/ai/expand-node": {}
  "/api/ai/extract-steps": {}
  "/api/ai/goal-map": {}
  "/api/ai/replan": {}
  "/api/ai/research": {}
  "/api/ai/unblock": {}
  "/api/ai/work-session": {}
  "/api/cron/notifications": {}
  "/api/gate": {}
  "/api/health": {}
  "/api/resource/resolve": {}
  "/api/stripe/checkout": {}
  "/api/stripe/portal": {}
  "/api/stripe/webhook": {}
  "/api/unsubscribe": {}
  "/app": {}
  "/app/admin": {}
  "/app/billing": {}
  "/app/inbox": {}
  "/app/map": {}
  "/app/notebook": {}
  "/app/review": {}
  "/app/settings": {}
  "/app/today": {}
  "/gate": {}
  "/onboarding": {}
  "/privacy": {}
  "/s/[token]": { "token": string; }
  "/sign-in": {}
  "/sign-up": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
