// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/admin">> = Specific
  const handler = {} as typeof import("../../app/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/billing">> = Specific
  const handler = {} as typeof import("../../app/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/inbox">> = Specific
  const handler = {} as typeof import("../../app/app/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/map">> = Specific
  const handler = {} as typeof import("../../app/app/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/notebook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/notebook">> = Specific
  const handler = {} as typeof import("../../app/app/notebook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/review">> = Specific
  const handler = {} as typeof import("../../app/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/settings">> = Specific
  const handler = {} as typeof import("../../app/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/today/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/today">> = Specific
  const handler = {} as typeof import("../../app/app/today/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gate">> = Specific
  const handler = {} as typeof import("../../app/gate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/s/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/[token]">> = Specific
  const handler = {} as typeof import("../../app/s/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/ask-node/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/ask-node">> = Specific
  const handler = {} as typeof import("../../app/api/ai/ask-node/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/ask-sola/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/ask-sola">> = Specific
  const handler = {} as typeof import("../../app/api/ai/ask-sola/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/clarify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/clarify">> = Specific
  const handler = {} as typeof import("../../app/api/ai/clarify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/draft">> = Specific
  const handler = {} as typeof import("../../app/api/ai/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/expand-node/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/expand-node">> = Specific
  const handler = {} as typeof import("../../app/api/ai/expand-node/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/extract-steps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/extract-steps">> = Specific
  const handler = {} as typeof import("../../app/api/ai/extract-steps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/goal-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/goal-map">> = Specific
  const handler = {} as typeof import("../../app/api/ai/goal-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/replan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/replan">> = Specific
  const handler = {} as typeof import("../../app/api/ai/replan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/research/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/research">> = Specific
  const handler = {} as typeof import("../../app/api/ai/research/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/unblock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/unblock">> = Specific
  const handler = {} as typeof import("../../app/api/ai/unblock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/work-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/work-session">> = Specific
  const handler = {} as typeof import("../../app/api/ai/work-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/cron/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gate">> = Specific
  const handler = {} as typeof import("../../app/api/gate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/resource/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resource/resolve">> = Specific
  const handler = {} as typeof import("../../app/api/resource/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/portal">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/api/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
