// Dark theme for Clerk's prebuilt components, matched to Solaspace's premium
// glossy language (raised-gold CTA, panel card, inset-well inputs, raised-btn).
export const clerkAppearance = {
  variables: {
    colorBackground: "transparent",
    colorText: "#f2f3f5",
    colorTextSecondary: "#9a9ea8",
    colorPrimary: "#e6b877",
    colorInputBackground: "rgba(0,0,0,0.22)",
    colorInputText: "#f2f3f5",
    colorNeutral: "#f2f3f5",
    colorDanger: "#d5896f",
    colorSuccess: "#8fae9f",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-sans)",
  },
  elements: {
    rootBox: "w-full",
    card: "panel rounded-2xl p-7 shadow-none",
    headerTitle: "font-display text-ink text-[22px] tracking-tight",
    headerSubtitle: "text-muted text-[14px]",
    socialButtonsBlockButton: "raised-btn text-ink border-0",
    socialButtonsBlockButtonText: "text-ink font-medium",
    dividerLine: "bg-line",
    dividerText: "text-faint font-mono text-[11px] uppercase tracking-[0.16em]",
    formFieldLabel: "text-muted text-[13px]",
    formFieldInput: "inset-well rounded-xl text-ink border-0 focus:shadow-none",
    formButtonPrimary: "raised-gold rounded-xl text-[15px] font-medium normal-case tracking-tight shadow-none after:hidden",
    formFieldInputShowPasswordButton: "text-muted hover:text-ink",
    otpCodeFieldInput: "inset-well text-ink border-0",
    footerActionText: "text-muted",
    footerActionLink: "text-accent hover:text-ink",
    identityPreviewText: "text-ink",
    identityPreviewEditButton: "text-accent",
    formResendCodeLink: "text-accent hover:text-ink",
    badge: "bg-accent/10 text-accent",
  },
} as const;
